name: Hellow workd
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build steps
        run: echo "FIrst action"

