name: Dopoloy static website
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Confgiure AWs cred
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
